from __future__ import annotations

UI_VERSION = "1.0.0-institutional-ui"

PASTICUAN_DASHBOARD_CSS = """
/* Presentation-only institutional skin. Calculation and rank semantics stay in legacy. */
.v9-wrap{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important;color:#e7eef6!important;background:#071019!important;border:1px solid #203244!important;border-radius:14px!important;padding:16px!important;box-shadow:none!important}
.v9-title{text-align:left!important;margin:2px 0 0!important;font-size:clamp(23px,3vw,36px)!important;font-weight:720!important;letter-spacing:-.035em!important;color:#f3f7fb!important}.v9-title b{color:#58c8b8!important;font-weight:720!important}
.v9-method{max-width:none!important;text-align:left!important;margin:10px 0 16px!important;padding:10px 12px!important;background:#0b1621!important;border:1px solid #1d3042!important;border-radius:9px!important;color:#8fa3b6!important;font-size:11px!important;line-height:1.5!important}.v9-method strong{color:#c7d6e4!important}.v9-method small{color:#7890a4!important}
.v9-card{position:relative!important;margin:12px 0!important;padding:13px!important;background:#0a1520!important;border:1px solid #203244!important;border-radius:12px!important;box-shadow:0 8px 24px rgba(0,0,0,.16)!important;overflow:hidden!important}.v9-card:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:#51687b}.v9-card.rank1:before{background:#18b89f}.v9-card.rank2:before{background:#b99a4b}.v9-card.rank3:before{background:#5c87ad}.v9-card.rank1,.v9-card.rank2,.v9-card.rank3{border-color:#203244!important}
.v9-card-head{display:grid!important;grid-template-columns:54px minmax(190px,2fr) minmax(115px,.72fr) minmax(155px,1fr) minmax(140px,.9fr)!important;gap:9px!important;align-items:stretch!important}
.v9-rank{border-radius:9px!important;background:#11231f!important;border:1px solid #245347!important;color:#d9f5ef!important}.rank2 .v9-rank{background:#211e13!important;border-color:#584c25!important;color:#f1e3b0!important}.rank3 .v9-rank{background:#101d28!important;border-color:#2c4d68!important;color:#d5e7f5!important}.v9-rank small{font-size:9px!important;letter-spacing:.08em!important;color:inherit!important;opacity:.7}.v9-rank strong{font-size:30px!important;font-variant-numeric:tabular-nums!important}
.v9-identity,.v9-score,.v9-rec,.v9-price{padding:10px 11px!important;border-radius:9px!important;background:#0d1925!important;border:1px solid #203244!important}.v9-identity h2{font-size:29px!important;line-height:1!important;letter-spacing:-.025em!important;color:#f5f8fb!important}.v9-identity p{margin:5px 0 2px!important;color:#9eb0c0!important;font-size:10px!important}.v9-identity em{color:#58c8b8!important;font-size:10px!important;letter-spacing:.04em!important}.v9-chip{margin:6px 4px 0 0!important;padding:2px 6px!important;background:#101f2d!important;border:1px solid #294055!important;border-radius:5px!important;color:#9fb3c4!important;font-size:8px!important;font-weight:650!important}
.v9-score span,.v9-rec span,.v9-price span{font-size:8px!important;letter-spacing:.08em!important;color:#778da1!important}.v9-score strong{font-size:36px!important;color:#69d7c6!important;font-variant-numeric:tabular-nums!important}.v9-score small,.v9-rec small,.v9-price small{color:#8298aa!important;font-size:8px!important}.v9-rec strong{font-size:17px!important;margin:5px 0!important}.v9-price strong{font-size:20px!important;margin:5px 0!important;font-variant-numeric:tabular-nums!important}.v9-rec.green strong{color:#63d6a8!important}.v9-rec.gold strong{color:#d7bc68!important}.v9-rec.orange strong{color:#d99b63!important}.v9-rec.blue strong{color:#75a9d4!important}.v9-rec.red strong{color:#d87570!important}
.v9-auth{margin-top:9px!important;padding:8px 10px!important;border-radius:8px!important;background:#0c1823!important;border:1px solid #203244!important;font-size:8px!important}.v9-auth strong{font-size:9px!important;letter-spacing:.03em!important}.v9-auth span,.v9-auth small{color:#8195a7!important}.v9-auth.green strong{color:#63d6a8!important}.v9-auth.gold strong{color:#d7bc68!important}.v9-auth.red strong{color:#d87570!important}
.v9-gates{gap:6px!important;margin-top:7px!important}.v9-gates span{padding:6px!important;border-radius:7px!important;background:#0c1823!important;border:1px solid #203244!important;color:#72899c!important;font-size:8px!important;letter-spacing:.04em!important}.v9-gates b{color:#d7e1e9!important}
.v9-grid-main{grid-template-columns:1fr 1.2fr .95fr!important;gap:9px!important;margin-top:9px!important}.v9-grid-bottom{grid-template-columns:.9fr 1.15fr 1fr!important;gap:9px!important;margin-top:9px!important}.v9-panel{background:#0c1823!important;border:1px solid #203244!important;border-radius:9px!important;padding:10px!important}.v9-panel h3{text-align:left!important;color:#8fa6b8!important;font-size:9px!important;letter-spacing:.09em!important;margin:0 0 9px!important}
.v9-plan-row{padding:5px 0!important;border-bottom:1px solid rgba(83,111,134,.18)!important;font-size:9px!important;color:#91a5b5!important}.v9-plan-row b{color:#d8e2e9!important;font-variant-numeric:tabular-nums!important}.v9-plan-row.stop b{color:#dc7b75!important}.v9-plan-row.target b{color:#69d3a7!important}
.v9-factor{grid-template-columns:105px 1fr 26px!important;gap:7px!important;font-size:9px!important;margin:6px 0!important;color:#90a5b6!important}.v9-factor b{font-variant-numeric:tabular-nums!important;color:#cdd8e0!important}.v9-bar{height:5px!important;background:#152637!important}.v9-bar i{background:#28a995!important}
.v9-gauge{width:98px!important;height:98px!important;background:conic-gradient(#2bb49e var(--pct),#5b2930 0)!important}.v9-gauge:before{width:72px!important;height:72px!important;background:#0c1823!important}.v9-gauge strong{font-size:20px!important}.v9-gauge small{font-size:7px!important;color:#8399aa!important}.v9-flow-stats{font-size:8px!important}.v9-flow-stats span{padding:5px!important;background:#101e2b!important;border:1px solid #1c3042!important}.v9-flow p{font-size:7px!important;color:#6f879a!important}
.v9-report-row{font-size:9px!important;border-bottom:1px solid rgba(83,111,134,.16)!important}.v9-report-row b{color:#cfb660!important}.v9-reasons{font-size:9px!important}.v9-reasons li{padding:4px 0!important}.v9-reasons li.positive span{color:#63d6a8!important}.v9-reasons li.developing span{color:#d7bc68!important}.v9-reasons li.warning span{color:#d99b63!important}.v9-highlight p{font-size:9px!important;line-height:1.55!important;color:#c7d3dc!important}.v9-highlight small{color:#71889a!important;font-size:8px!important}.v9-confidence{padding:6px!important;border-radius:6px!important;background:#101e2b!important;font-size:8px!important;letter-spacing:.05em!important}
.v9-cost-basis{margin-top:8px!important;padding:8px 9px!important;border:1px solid #234154!important;border-radius:7px!important;background:#0f1d29!important;text-align:left!important}.v9-cost-basis span{display:block;color:#7894a6!important;font-size:7px!important;font-weight:750;letter-spacing:.08em}.v9-cost-basis strong{display:block;color:#69d7c6!important;font-size:12px!important;margin:3px 0}.v9-cost-basis small,.v9-cost-basis em{display:block;color:#8095a6!important;font-size:7px!important;font-style:normal!important;line-height:1.4}
.v9-footer{margin-top:12px!important;padding:9px 0 0!important;border-top:1px solid #203244!important;color:#637b8e!important;font-size:8px!important}
@media(max-width:980px){.v9-card-head{grid-template-columns:50px 1.5fr 100px!important}.v9-rec,.v9-price{grid-column:span 1}.v9-grid-main,.v9-grid-bottom{grid-template-columns:1fr!important}.v9-auth{grid-template-columns:1fr!important}.v9-identity h2{font-size:25px!important}}
@media(max-width:640px){.v9-wrap{padding:8px!important;border-radius:10px!important}.v9-title{font-size:22px!important}.v9-method{font-size:9px!important;margin-bottom:10px!important}.v9-card{padding:9px!important}.v9-card-head{grid-template-columns:42px 1fr!important}.v9-score,.v9-rec,.v9-price{grid-column:span 1!important}.v9-score strong{font-size:31px!important}.v9-rank strong{font-size:26px!important}.v9-gates{grid-template-columns:1fr!important}.v9-factor{grid-template-columns:94px 1fr 24px!important}}
"""

__all__ = ["UI_VERSION", "PASTICUAN_DASHBOARD_CSS"]
