-- IDX Super Scanner database foundation v2 (Supabase/PostgreSQL)
-- Model target: v6.9.0-confidence-database-foundation
-- Run once in Supabase SQL Editor on a new project.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Stable issuer/source layer. These tables store facts, not model scores.
-- ---------------------------------------------------------------------------
create table if not exists public.issuer_master (
    ticker text primary key,
    company_name text,
    sector text,
    subsector text,
    listing_date date,
    currency_default text,
    company_website text,
    investor_relations_url text,
    is_syariah boolean,
    des_effective_date date,
    des_source_url text,
    last_verified_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.source_documents (
    document_id text primary key,
    ticker text references public.issuer_master(ticker) on update cascade on delete set null,
    document_type text,
    source_family text,
    source_url text,
    published_at timestamptz,
    fetched_at timestamptz,
    period_end date,
    revision_number integer not null default 0,
    sha256 text,
    content_length bigint,
    storage_path text,
    parse_status text,
    parse_error text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (ticker, document_type, period_end, revision_number, sha256)
);

create table if not exists public.financial_periods (
    financial_period_id uuid primary key default gen_random_uuid(),
    ticker text not null references public.issuer_master(ticker) on update cascade on delete cascade,
    period_end date not null,
    period_type text not null,
    filing_date date,
    statement_basis text not null default 'CONSOLIDATED',
    audit_status text,
    currency text,
    unit_multiplier numeric,
    revision_number integer not null default 0,
    source_family text,
    source_url text,
    document_id text references public.source_documents(document_id) on update cascade on delete set null,
    document_hash text,
    is_current boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (ticker, period_end, period_type, statement_basis, revision_number)
);

create table if not exists public.financial_facts (
    financial_fact_id uuid primary key default gen_random_uuid(),
    financial_period_id uuid not null references public.financial_periods(financial_period_id) on delete cascade,
    ticker text not null,
    metric_code text not null,
    taxonomy_tag text,
    reported_value numeric,
    normalized_value numeric,
    currency text,
    unit_multiplier numeric,
    fact_context text,
    source_lineage jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (financial_period_id, metric_code, fact_context)
);

-- ---------------------------------------------------------------------------
-- Versioned model snapshots. snapshot_id is generated by the scanner and is
-- the idempotency key used by PostgREST upsert.
-- ---------------------------------------------------------------------------
create table if not exists public.fundamental_snapshots (
    snapshot_id text primary key,
    scan_id text,
    ticker text not null,
    period_end text,
    statement_date text,
    fundamental_score numeric,
    fundamental_score_10 numeric,
    fundamental_coverage numeric,
    fundamental_data_grade text,
    fundamental_reliability numeric,
    revenue_growth numeric,
    earnings_growth numeric,
    roe numeric,
    roa numeric,
    roic_proxy numeric,
    net_margin numeric,
    operating_margin numeric,
    operating_cash_flow numeric,
    free_cash_flow numeric,
    cash_conversion_ttm numeric,
    debt_equity numeric,
    net_debt_ebitda numeric,
    interest_coverage numeric,
    market_cap numeric,
    fundamental_source_families text,
    fundamental_official_verified boolean,
    statement_age_days numeric,
    as_of timestamptz not null,
    model_version text not null,
    schema_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.multibagger_snapshots (
    snapshot_id text primary key,
    scan_id text,
    ticker text not null,
    multibagger_status text,
    multibagger_quality_score numeric,
    execution_readiness_score numeric,
    research_recommendation_status text,
    multibagger_candidate_type text,
    multibagger_lane text,
    research_eligible boolean,
    research_eligibility_reason text,
    portfolio_allocation_eligible boolean,
    growth_compounder_score numeric,
    growth_compounder_base_score numeric,
    growth_compounder_selection_score numeric,
    turnaround_recovery_score numeric,
    confidence_adjusted_turnaround_score numeric,
    turnaround_selection_score numeric,
    turnaround_research_state text,
    turnaround_recovery_signals integer,
    turnaround_gate_reasons text,
    critical_research_flags boolean,
    operational_recovery_flags boolean,
    effective_silent_accumulation_score numeric,
    economic_earnings_score numeric,
    economic_earnings_confidence numeric,
    minority_leakage_pct numeric,
    ocf_ebitda_conversion numeric,
    silent_accumulation_score numeric,
    silent_accumulation_state text,
    silent_accumulation_confidence numeric,
    silent_accumulation_v4_adjustment numeric,
    accumulation_persistence_score numeric,
    accumulation_positive_windows_pct numeric,
    accumulation_longest_run integer,
    accumulation_regime text,
    absorption_confirmed_days20 integer,
    failed_absorption_days20 integer,
    effort_result_absorption20 integer,
    effort_result_distribution20 integer,
    persistent_bid_score numeric,
    data_confidence_score numeric,
    fundamental_confidence_score numeric,
    future_fundamental_confidence_score numeric,
    technical_confidence_score numeric,
    eoff_confidence_score numeric,
    overall_research_confidence numeric,
    overall_research_confidence_grade text,
    confidence_adjusted_multibagger_score numeric,
    top_positive_drivers text,
    top_negative_drivers text,
    scoring_reason_codes text,
    project_pipeline_score numeric,
    project_stage text,
    project_stage_probability_pct numeric,
    project_success_probability_pct numeric,
    future_fundamental_impact_score numeric,
    best_buy_date text,
    best_buy_window_start text,
    best_buy_window_end text,
    eoff_state text,
    eoff_reconstruction_score numeric,
    eoff_public_validation_state text,
    eoff_public_lift numeric,
    last_price numeric,
    as_of timestamptz not null,
    model_version text not null,
    schema_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.technical_snapshots (
    snapshot_id text primary key,
    scan_id text,
    ticker text not null,
    last_price numeric,
    active_setup text,
    technical_entry_state text,
    entry numeric,
    stop_loss numeric,
    tp1 numeric,
    tp2 numeric,
    execution_readiness_score numeric,
    silent_accumulation_score numeric,
    silent_accumulation_confidence numeric,
    accumulation_persistence_score numeric,
    accumulation_regime text,
    relative_strength60 numeric,
    roc60 numeric,
    roc120 numeric,
    adtv20_idr numeric,
    as_of timestamptz not null,
    model_version text not null,
    schema_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.eoff_predictions (
    snapshot_id text primary key,
    scan_id text,
    ticker text not null,
    best_buy_date text,
    best_buy_window_start text,
    best_buy_window_end text,
    best_buy_score numeric,
    best_buy_confidence numeric,
    best_buy_entry_low numeric,
    best_buy_entry_high numeric,
    best_buy_trigger numeric,
    eoff_state text,
    eoff_reconstruction_score numeric,
    eoff_strength_label text,
    eoff_direction_bias text,
    eoff_public_validation_state text,
    eoff_public_directional_events integer,
    eoff_public_lift numeric,
    time_cycle_confidence numeric,
    as_of timestamptz not null,
    model_version text not null,
    schema_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.project_master (
    project_id uuid primary key default gen_random_uuid(),
    ticker text not null references public.issuer_master(ticker) on update cascade on delete cascade,
    project_name text not null,
    project_type text,
    economic_ownership_pct numeric,
    announced_at date,
    expected_cod date,
    actual_cod date,
    capex_total numeric,
    currency text,
    latest_stage text,
    latest_confidence numeric,
    last_verified_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (ticker, project_name)
);

create table if not exists public.project_events (
    snapshot_id text primary key,
    scan_id text,
    ticker text not null,
    project_name text,
    project_names text,
    project_stage text,
    project_completion_pct numeric,
    project_funding_secured_pct numeric,
    project_ownership_pct numeric,
    project_capex_idr numeric,
    project_expected_revenue_idr numeric,
    project_expected_ebitda_idr numeric,
    project_data_coverage numeric,
    project_source_families text,
    project_source_urls text,
    project_source_quorum_verified boolean,
    project_execution_flags text,
    last_verified_at text,
    review_origin text,
    event_date text,
    as_of timestamptz not null,
    model_version text not null,
    schema_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.management_roles (
    management_role_id uuid primary key default gen_random_uuid(),
    ticker text not null references public.issuer_master(ticker) on update cascade on delete cascade,
    person_name text not null,
    role text not null,
    appointment_date date,
    end_date date,
    rups_date date,
    shares_owned_pct numeric,
    source_document_id text references public.source_documents(document_id) on update cascade on delete set null,
    source_url text,
    verified boolean not null default false,
    evidence_confidence numeric,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (ticker, person_name, role, appointment_date)
);

create table if not exists public.ownership_events (
    ownership_event_id uuid primary key default gen_random_uuid(),
    ticker text not null references public.issuer_master(ticker) on update cascade on delete cascade,
    holder_name text not null,
    holder_type text,
    ownership_pct_before numeric,
    ownership_pct_after numeric,
    shares_change numeric,
    transaction_date date,
    report_date date,
    pledged_pct numeric,
    source_document_id text references public.source_documents(document_id) on update cascade on delete set null,
    source_url text,
    verified boolean not null default false,
    created_at timestamptz not null default now(),
    unique (ticker, holder_name, transaction_date, shares_change)
);

create table if not exists public.corporate_events (
    corporate_event_id uuid primary key default gen_random_uuid(),
    ticker text not null references public.issuer_master(ticker) on update cascade on delete cascade,
    event_type text not null,
    event_date date,
    published_at timestamptz,
    materiality numeric,
    event_status text,
    source_document_id text references public.source_documents(document_id) on update cascade on delete set null,
    source_url text,
    document_hash text,
    verified boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (ticker, event_type, event_date, document_hash)
);

create table if not exists public.scan_runs (
    snapshot_id text primary key,
    scan_id text not null unique,
    started_at timestamptz,
    finished_at timestamptz,
    ticker_count integer,
    prepared_count integer,
    multibagger_count integer,
    core_swing_count integer,
    database_mode text,
    as_of timestamptz not null,
    model_version text not null,
    schema_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.provider_health (
    snapshot_id text primary key,
    scan_id text,
    provider text,
    scope text,
    status text,
    rows numeric,
    asof text,
    error text,
    error_code text,
    source_family text,
    as_of timestamptz not null,
    model_version text not null,
    schema_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Realised outcomes are intentionally separate from predictions to prevent
-- accidental look-ahead leakage when backtesting.
create table if not exists public.eoff_outcomes (
    outcome_id uuid primary key default gen_random_uuid(),
    prediction_snapshot_id text not null references public.eoff_predictions(snapshot_id) on delete cascade,
    actual_pivot_date date,
    forward_return_5d numeric,
    forward_return_10d numeric,
    forward_return_20d numeric,
    mae_10d numeric,
    mfe_10d numeric,
    hit_exact boolean,
    hit_near_3d boolean,
    evaluated_at timestamptz not null default now(),
    unique (prediction_snapshot_id)
);

-- ---------------------------------------------------------------------------
-- Indexes for dashboard/latest-snapshot queries.
-- ---------------------------------------------------------------------------
create index if not exists idx_financial_periods_ticker_period on public.financial_periods (ticker, period_end desc);
create index if not exists idx_financial_facts_ticker_metric on public.financial_facts (ticker, metric_code);
create index if not exists idx_fundamental_snapshots_ticker_asof on public.fundamental_snapshots (ticker, as_of desc);
create index if not exists idx_multibagger_snapshots_ticker_asof on public.multibagger_snapshots (ticker, as_of desc);
create index if not exists idx_multibagger_rank on public.multibagger_snapshots (confidence_adjusted_multibagger_score desc nulls last, overall_research_confidence desc nulls last);
create index if not exists idx_multibagger_growth_lane_rank on public.multibagger_snapshots (growth_compounder_selection_score desc nulls last) where research_eligible is true and multibagger_lane = 'GROWTH_COMPOUNDER';
create index if not exists idx_multibagger_turnaround_lane_rank on public.multibagger_snapshots (turnaround_selection_score desc nulls last) where research_eligible is true and multibagger_lane = 'TURNAROUND_CYCLICAL';
create index if not exists idx_technical_snapshots_ticker_asof on public.technical_snapshots (ticker, as_of desc);
create index if not exists idx_eoff_predictions_ticker_asof on public.eoff_predictions (ticker, as_of desc);
create index if not exists idx_project_events_ticker_asof on public.project_events (ticker, as_of desc);
create index if not exists idx_provider_health_asof on public.provider_health (as_of desc, provider);
create index if not exists idx_scan_runs_asof on public.scan_runs (as_of desc);

-- Latest snapshot views used for read-first integration later.
create or replace view public.latest_fundamental_snapshots
with (security_invoker = true) as
select distinct on (ticker) *
from public.fundamental_snapshots
order by ticker, as_of desc;

create or replace view public.latest_multibagger_snapshots
with (security_invoker = true) as
select distinct on (ticker) *
from public.multibagger_snapshots
order by ticker, as_of desc;

create or replace view public.latest_technical_snapshots
with (security_invoker = true) as
select distinct on (ticker) *
from public.technical_snapshots
order by ticker, as_of desc;

-- ---------------------------------------------------------------------------
-- Security: all exposed public tables use RLS. The scanner writes only with a
-- backend secret/service-role key stored in Streamlit Secrets. No anon or
-- authenticated policies are created by this script.
-- ---------------------------------------------------------------------------
do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'issuer_master','source_documents','financial_periods','financial_facts',
        'fundamental_snapshots','multibagger_snapshots','technical_snapshots',
        'eoff_predictions','eoff_outcomes','project_master','project_events',
        'management_roles','ownership_events','corporate_events','scan_runs','provider_health'
    ]
    loop
        execute format('alter table public.%I enable row level security', table_name);
        execute format('revoke all on table public.%I from anon, authenticated', table_name);
        execute format('grant all on table public.%I to service_role', table_name);
    end loop;
end $$;

revoke all on table public.latest_fundamental_snapshots from anon, authenticated;
revoke all on table public.latest_multibagger_snapshots from anon, authenticated;
revoke all on table public.latest_technical_snapshots from anon, authenticated;
grant select on table public.latest_fundamental_snapshots to service_role;
grant select on table public.latest_multibagger_snapshots to service_role;
grant select on table public.latest_technical_snapshots to service_role;
grant usage on schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
